.. NOTE: we are now using links to highlight new functions and classes.
   Please follow the examples below like 
   :func:`julearn.api.run_cross_validation`, so the
   whats_new page will have a link to the function/class documentation.

.. NOTE: there are 3 separate sections for changes, based on type:
   - "Enhancements" for new features
   - "Bugs" for bug fixes
   - "API changes" for backward-incompatible changes

.. _current:

Current (0.2.6.dev)
-------------------

Enhancements
~~~~~~~~~~~~

- Make CBPM use sum by default  (:gh:`170` by `Sami Hamdan`_).

Bugs
~~~~


- ADD BaseEstimator to ConfoundRemoval for Target  (:gh:`151` by `Sami Hamdan`_).

API changes
~~~~~~~~~~~


