.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. sklearn

.. _scikit-learn: https://scikit-learn.org/stable/
.. _`Balanced Accuracy`: https://scikit-learn.org/stable/modules/model_evaluation.html#balanced-accuracy-score
.. _`Precision`: https://scikit-learn.org/stable/modules/model_evaluation.html#precission-score
.. _`Metrics`: https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics
.. _`Cross Validation`: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.model_selection
.. _`Hyperparameter Tunning`: https://scikit-learn.org/stable/modules/grid_search.html

.. _`Standard Scaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
.. _`StandardScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
.. _`Robust Scaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html
.. _`RobustScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html
.. _`MinMaxScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
.. _`MaxAbsScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MaxAbsScaler.html
.. _`Normalizer`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html
.. _`QuantileTransformer`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html
.. _`PowerTransformer`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PowerTransformer.html

.. _`GenericUnivariateSelect`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.GenericUnivariateSelect.html
.. _`SelectPercentile`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectPercentile.html
.. _`SelectKBest`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html
.. _`SelectFdr`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFdr.html
.. _`SelectFpr`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFpr.html
.. _`SelectFwe`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFwe.html
.. _`VarianceThreshold`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html

.. _`PCA`: https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

.. _`SVC`: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
.. _`SVR`: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

.. _`Random Forest`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
.. _`RandomForestClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html


.. _`GridSearchCV`: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV
.. _`RandomizedSearchCV`: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#sklearn.model_selection.RandomizedSearchCV


.. _`pandas`: https://pandas.pydata.org
.. _`Python`: https://python.org
.. _`seaborn`: https://seaborn.pydata.org

.. _`venv`: https://docs.python.org/3/tutorial/venv.html
.. _`conda env`: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

.. _`Github`: https://github.com/
.. _`julearn Github`: https://github.com/juaml/julearn

.. _`Wikipedia`: https://wikipedia.org

.. _`Regular Expressions`: https://docs.python.org/3/library/re.html

.. _`setuptools_scm`: https://github.com/pypa/setuptools_scm/
