.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. sklearn

.. _scikit-learn: https://scikit-learn.org/stable/
.. _`Balanced Accuracy`: https://scikit-learn.org/stable/modules/model_evaluation.html#balanced-accuracy-score
.. _`Precision`: https://scikit-learn.org/stable/modules/model_evaluation.html#precission-score
.. _`Metrics`: https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics