.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. _`AML`: https://www.fz-juelich.de/inm/inm-7/EN/Forschung/Applied%20Machine%20Learning/_node.html
.. _`INM-7`: https://www.fz-juelich.de/inm/inm-7/EN/Home/home_node.html
.. _`video tutorial`: https://youtube.com/playlist?list=PLvb39y5Ge21CUjccmY_0kXRCwBBaikGf_
.. sklearn

.. _scikit-learn: https://scikit-learn.org/stable/
.. _`Balanced Accuracy`: https://scikit-learn.org/stable/modules/model_evaluation.html#balanced-accuracy-score
.. _`Precision`: https://scikit-learn.org/stable/modules/model_evaluation.html#precission-score
.. _`scoring`: https://scikit-learn.org/stable/modules/model_evaluation.html#
.. _`Metrics`: https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics
.. _`Cross Validation`: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.model_selection
.. _`Hyperparameter Tuning`: https://scikit-learn.org/stable/modules/grid_search.html

.. _`Standard Scaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
.. _`StandardScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
.. _`Robust Scaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html
.. _`RobustScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html
.. _`MinMaxScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
.. _`MaxAbsScaler`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MaxAbsScaler.html
.. _`Normalizer`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html
.. _`QuantileTransformer`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html
.. _`PowerTransformer`: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PowerTransformer.html

.. _`GenericUnivariateSelect`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.GenericUnivariateSelect.html
.. _`SelectPercentile`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectPercentile.html
.. _`SelectKBest`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html
.. _`SelectFdr`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFdr.html
.. _`SelectFpr`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFpr.html
.. _`SelectFwe`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFwe.html
.. _`VarianceThreshold`: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html

.. _`PCA`: https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

.. _`SVC`: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
.. _`SVR`: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

.. _`Random Forest`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
.. _`RandomForestClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
.. _`RandomForestRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
.. _`ExtraTreesClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html
.. _`ExtraTreesRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesRegressor.html
.. _`AdaBoostClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html
.. _`AdaBoostRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostRegressor.html
.. _`BaggingClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html
.. _`BaggingRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingRegressor.html
.. _`GradientBoostingClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html
.. _`GradientBoostingRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

.. _`GaussianProcessClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html
.. _`GaussianProcessRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html

.. _`LogisticRegression`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
.. _`LogisticRegressionCV`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html
.. _`LinearRegression`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
.. _`RidgeClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeClassifier.html
.. _`Ridge`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html
.. _`RidgeClassifierCV`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeClassifierCV.html
.. _`RidgeCV`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html
.. _`SGDClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html
.. _`SGDRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html


.. _`BernoulliNB`: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html
.. _`CategoricalNB`: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.CategoricalNB.html
.. _`ComplementNB`: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.ComplementNB.html
.. _`GaussianNB`: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html
.. _`MultinomialNB`: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html


.. _`DummyClassifier`: https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html
.. _`DummyRegressor`: https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyRegressor.html


.. _`GridSearchCV`: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV
.. _`RandomizedSearchCV`: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#sklearn.model_selection.RandomizedSearchCV

.. _`make_scorer`: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.make_scorer.html?highlight=make_scorer#sklearn.metrics.make_scorer

.. _`pandas`: https://pandas.pydata.org
.. _`pandas.DataFrame` : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

.. _`Python`: https://python.org
.. _`seaborn`: https://seaborn.pydata.org
.. _`matplotlib`: https://matplotlib.org

.. _`venv`: https://docs.python.org/3/tutorial/venv.html
.. _`conda env`: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

.. _`Github`: https://github.com/
.. _`julearn Github`: https://github.com/juaml/julearn

.. _`Wikipedia`: https://wikipedia.org

.. _`Regular Expressions`: https://docs.python.org/3/library/re.html

.. _`setuptools_scm`: https://github.com/pypa/setuptools_scm/

.. _`sphinx gallery`: https://sphinx-gallery.github.io/stable/index.html
.. _`sphinx RST reference`: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup


.. numpy
.. _`numpy`: https://numpy.org
.. _`numpy.array`: https://numpy.org/doc/stable/reference/generated/numpy.array.html
.. _`numpy.corrcoef`: https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html