name: Build and publish docs

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        # require all of history to see all tagged versions' docs
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Install Python dependencies
      run: |
        uv sync --locked --extra docs

    - name: Checkout gh-pages
      # As we already did a deploy of gh-pages above, it is guaranteed to be there
      # so check it out so we can selectively build docs below
      uses: actions/checkout@v6
      with:
          ref: gh-pages
          path: docs/_build

    - name: Build docs
      # Use the args we normally pass to sphinx-build, but run sphinx-polyversion
      run: |
        uv run make -C docs/ html
        touch docs/_build/.nojekyll
        cp docs/redirect.html docs/_build/index.html
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        keep_files: true
