name: Build and preview docs

on:
  push:
    branches-ignore:
      - "main"
    tags-ignore:
      - v*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        if: github.event.action != 'closed' # We don't need the build if we know the preview will be removed
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        if: github.event.action != 'closed' # We don't need the build if we know the preview will be removed
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Install Python dependencies
        if: github.event.action != 'closed' # We don't need the build if we know the preview will be removed
        run: |
          uv sync --locked --extra docs

      - name: Test build docs
        if: github.event.action != 'closed' # We don't need the build if we know the preview will be removed
        run: |
          uv run make -C docs/ local

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs/_build/dev
        if: github.event_name == 'pull_request'
