name: Build and preview docs

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - v*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[docs,viz]
    - name: Test build docs
      run: |
        BUILDDIR=_build/main make -C docs/ local
    - name: Deploy preview
      if: github.event_name == 'pull_request'
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: docs/_build/main
